### ISSUE TITLE
Additional constructors for GeoArray?

### ISSUE THREAD

**Issue by vlandau** [rafaqz/Rasters.jl#112]
Are there existing methods to create a GeoArray from an array and lat and lon dims, or from an array, WKT projection, and geo transform (or would it be easy to add them)?

I'm developing a new package to construct graphs (and compute various metrics, least cost paths, etc) from raster data. I'm hoping to add methods for `GeoData.GeoArray`s and these extra methods would make it super easy!

**Comment by rafaqz** [comment]
Should be easy enough to do:

```julia
lonvals = range from the geotransform
latvals = range from the geotransform
crs = WellKnownText(wkt_string),
lat = Lat(lonvals; mode=Projected(order=Ordered(), sampling=Points(), crs=crs, mappedcrs=EPSG(4236)))
lon = Lon(latvals; mode=Projected(order=Ordered(), sampling=Points(), crs=crs, mappedcrs=EPSG(4236)))
A = GeoArray(A, (lat, lon))
```
You may need to use `Ordered(index=ReverseIndex())`, `sampling=Intervals(Center())` etc to match your array properties, or drop them if the defaults are fine. `span=Regular(stepsize)` should be detected for you if `latvals` is a range.

There is code to convert a GDAL geotransform to `latvals`/`lonvals` in sources/gdal.jl:

https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/gdal.jl#L220-L228

It should really be separated out a bit more cleanly but I think those lines do what you want.

Maybe a constructor for something like this would be helpful too.

**Comment by rafaqz** [comment]
These examples no longer work the same way, closing this
