### ISSUE TITLE
Low efficiency of `RasterDiskArray `

### ISSUE THREAD

**Issue by kongdd** [rafaqz/Rasters.jl#254]
It seems `Rasters.read` in a extremely low efficiency. It is about 6 times slower than NCDatasets.
Any idea how to improve this?

An unperfect, but practical solution by adding a parameter to escape DiskArray: 
<https://github.com/jl-spatial/Rasters.jl/commit/bc121728cffe506c21afa8e35f550a3cb0294f9a>

**Comment by kongdd** [comment]
```julia
using NCDatasets
using Rasters

f = "clusterId_HI_Tmax_(1961-2016).nc"

# option1
nc = NCDataset(f)
@time data = nc["clusterId"][:];

# option2
x = Raster(f, key = "clusterId")
@time data = read(x);
```
The input file is available at [here](https://mail2sysueducn-my.sharepoint.com/:u:/g/personal/kongdd_mail2_sysu_edu_cn/EbdgY0KqW3lEm8CoY87hKdsBCAXfF1QgaPh4QOG3lRN8Fw?e=bzcV6y).

**Comment by kongdd** [comment]
I think add the parameter `lazy` is the simplest solution,if this issue is not the problem of `RasterDiskArray `.

**Comment by kongdd** [comment]
The function `RasterStack` might have the same issue.

**Comment by kongdd** [comment]
Same issue in reading tiff files:

```julia
using Stars # the GeoArrays backends
using Rasters

f = "/mnt/h/global_WB/ET/diagnosed_PML/PMLV2_v016/PMLV2_yearly_G010_v014_2017-01-01.tif"

@time r = read(Raster(f))
  9.392881 seconds (4.11 M allocations: 793.161 MiB, 2.68% gc time, 10.45% compilation time)
3600×1500×7 Raster{Float64,3} with dimensions:
  X Projected range(-180.0, stop=179.9, length=3600) ForwardOrdered Regular Intervals crs: WellKnownText,
  Y Projected range(89.9, stop=-60.0, length=1500) ReverseOrdered Regular Intervals crs: WellKnownText,
  Band Categorical 1:7 ForwardOrdered

@time r1 = Stars.rast(f)
  1.427316 seconds (128 allocations: 292.901 MiB, 1.16% gc time)
3600x1500x7 Array{Float64, 3} with AffineMap([0.1 0.0; 0.0 -0.1], [-180.0, 90.0]) and CRS GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
```
Seems that it is a prevalent issues, not only for big nc files.

> The tiff file at [here](https://mail2sysueducn-my.sharepoint.com/:i:/g/personal/kongdd_mail2_sysu_edu_cn/EZuLdvRl9dFHp0zq_QW48isB-ap4l11oTCECSIozWTOAkg?e=g3jR5o)

**Comment by rafaqz** [comment]
Thanks for looking into this, it actually seems like something is a lot slower with tifs now than in the past.

Lets make a `lazy` flag for all backends and make `false` the default. When you have data big enough to need it, opting in with `lazy=true` is not a huge issue.

We will also need to speed up the lazy loading, it really shouldn't be this slow.

**Comment by kongdd** [comment]
Glad to know that you agree with adding the parameter `lazy`. Hope this issue can be solved. 
Rasters.jl is a good replacement of R package Terra.

**Comment by rafaqz** [comment]
See the PR for a partial fix that also fixes lazy loading time. We can also still add the `lazy` flag.

I also want to say thank you for all your input lately, this kind of feedback really appreciated and key to improving the quality of the package and making it a good replacement for e.g. terra. If I take a few days to reply sometimes its just that I'm too busy at the moment, not that I disagree with your issue!

**Comment by kongdd** [comment]
Just wondering, is adding the `lazy` flag still on the plan?

**Comment by rafaqz** [comment]
Yes probably a good idea.
