### ISSUE TITLE
rasterize broken documentation

### ISSUE THREAD

**Issue by maartenvd** [rafaqz/Rasters.jl#273]
just a headsup - the example where a shapefile gets rasterized is broken. https://rafaqz.github.io/Rasters.jl/stable/#Rasters.rasterize

My usecase is that I have 2 shapefiles with different coordinate systems. I want to convert them to the same format, and then plot them. Is Rasters the right package for the job?

**Comment by rafaqz** [comment]
Thanks, sorry something recent must have broken it. I'm actually rewriting that for the new GeoInterface 1.0 currently, so it will be working soon. An older version will also work.

And no. Raster.jl doesn't manipulate shape data, it just uses existing geometries for rasterizing/masking etc. You can problably do that conversion with ArchGDAL.jl. And geometries will plot with Plots.jl automatically.

**Comment by maartenvd** [comment]
Indeed, archgdal turns out to be what I need :)
