### ISSUE TITLE
Problem while plotting a Raster from an ArchGDAL.jl-generated raster file

### ISSUE THREAD

**Issue by jguerber** [rafaqz/Rasters.jl#284]
Hi !

I'm currently experimenting with a RasterDataSources.jl fork and I'm running into bad plots when creating a `Raster` from a .tif file built with ArchGDAL.jl.

A MWE for creating a .tif file that raises this issue is the minimal example for raster writing with ArchGDAL.jl :

```julia
using ArchGDAL

Z = rand(240, 180)
ArchGDAL.create(
    "./test.tif",
    driver = ArchGDAL.getdriver("GTiff"),
    width=240,
    height=180,
    nbands=1,
    dtype=Float32
) do dataset
    ArchGDAL.write!(dataset, Z, 1)
end
```
Now when I try to create a `Raster` from the file and plot it, using 

```julia
using Plots, Rasters
raster = Raster("test.tif")
plot(raster) # produces broken plots
```
I get broken plots like this one (using Plotly): 

![broken](https://user-images.githubusercontent.com/95242763/184155415-297407f9-c0d3-4b65-800e-32feae9e7287.svg)

PlotlyBackend does not issue any message and GRBackend complains with: 

```
GKS: Rectangle definition is invalid in routine SET_VIEWPORT
y points not sorted in ascending order
GKS: Viewport is not within the NDC unit square in routine SET_VIEWPORT
```
I report this as an issue in Rasters.jl and not ArchGDAL.jl because trying to access the raster data with `getindex` works correctly, and opening it in an external software (tested with ImageJ) also works. Accurate plots can even be produced by re-building a second raster:
 
```julia
raster2 = Raster(Matrix(raster[:,:]), dims = (X(1:240), Y(1:180)))
plot(raster2) # works as intended
``` 
This last code chunk is an okay workaround for most uses but in my case I'd like not to introduce a circular dependency to Rasters.jl in my RasterDataSources.jl fork.

There might be a problem with the plot recipes, or I might be doing something wrong. Do you have any thoughts on this ?

**Comment by rafaqz** [comment]
Your'e not setting a geotransform. There seems to be a bug in handling the possibility that its empty. But its not much of a geotiff without any kind of spatial data at all, so rare in the wild!

One question is: why don't you create the file with Rasters.jl? Most of these things are easier to do here than in ArchGDAL, with less ways to shoot yourself in the foot.

```julia
rast = Raster(rand(X(240), Y(180))
write("test.tif", rast)
```

Or with dimension values you might want in the geotransform:
```julia
rast = Raster(rand(X(10:0.1:20), Y(9:0.1:19)))
write("test.tif", rast)
```

Rasters handles flipping the axes, ordering the dimensions, etc etc to match GDAL. Or netcdf. And there is no way to leave these things empty as in your example.

**Comment by jguerber** [comment]
Thanks a lot for the quick answer !

The problem was on my side indeed, calling `setgeotransform` with the right parameters (i.e. a negative y-resolution to go from a south-up matrix to a north-up raster) allowed to create a raster file that can be read with the current version of `Raster`.

FYI, I prefer creating the file with ArchGDAL.jl because i'm working in a fork of RasterDataSources.jl : introducing a dependency to Rasters.jl there would result in a circular dependency, which is, in my understanding of Julia packages, something to be avoided.

Closing this issue, and thanks for the fix, in this exact case I won't need it but it might be handy for other unorthodox use cases :)

**Comment by rafaqz** [comment]
It makes more sense to work in a new package depending onRasters.jl ;)

Working in a fork you will never PR almost never makes sense.

**Comment by jguerber** [comment]
Haha yeah i guess.. A PR might come one day (maybe even in the next month) if I get confident enough. Thanks for the tips anyway !

**Comment by rafaqz** [comment]
Great! but keep in mind PR with dependencies won't be merged.

The GDAL dep belongs in Rasters.jl and similar packages. RasteraDataSources.jl is just for downloading things.
