### ISSUE TITLE
RasterSeries built from a RasterDataSource contains copies of the first array (only in v0.4.1)

### ISSUE THREAD

**Issue by jguerber** [rafaqz/Rasters.jl#294]
Hello ! I found another weird behavior while playing around with the package.

Since the last version change, after creating a series from a RasterDataSource (or an AbstractArray of filenames), all the rasters in the series are exact copies of the first one.

```julia
ser = RasterSeries(WorldClim{Climate}, :prec; res="10m", month=Jan:March, mappedcrs=EPSG(4326))
ser[Ti(1)] == ser[Ti(2)] # false with v0.3.0, true with v0.4.1
```

I think this originates from ![the way metadata is copied over all the rasters in the series](https://github.com/rafaqz/Rasters.jl/blob/main/src/series.jl#L95), because this chunk builds a correctly-indexed series:

```julia
filenames = getraster(WorldClim{Climate}, :prec; res="10m", month=Jan:March)
ser2 = RasterSeries(filenames, Ti(Jan:Mar); duplicate_first = false)
ser2[Ti(1)] == ser[Ti(2)] # false with v0.3.0 and v0.4.1, correct
```

I'm not familiar with DimensionalData.jl and the problem might be there so I can't suggest any fix right now but i might get into it. Any ideas ?

**Comment by rafaqz** [comment]
Yeah just turn off `duplicate_first` for now. 

Probably `fakse` should be the default so its opt-in. The idea is it can be pretty slow to load the metadata of 100s of files upfront, and sometimes they're essentially the same except the main data. No idea why it's now duplicating that too...
