### ISSUE TITLE
`combine` is too slow

### ISSUE THREAD

**Issue by ayushpatnaikgit** [rafaqz/Rasters.jl#298]
Hi, 
I'm combining single band nighttime lights images over time. 

I am running the following code. 
```julia
using Rasters, Dates

# the directory "DATA" contains the tif files
filelist = readdir(joinpath(pwd(), "DATA"), join = true) # filelist is a vector of strings containing names of files in the dir.

# create timestamps across which the `RasterSeries` is to be made. I've put 
# some garbage values here (like 2012-01-01) at some specified times of the day.
timestamps = [
    year(DateTime("20080101T123012", dateformat"yyyymmddTHHMMSS")),
    year(DateTime("20090201T123012", dateformat"yyyymmddTHHMMSS")),
    year(DateTime("20100301T123012", dateformat"yyyymmddTHHMMSS")),
]

series = RasterSeries(filelist, Ti(timestamps))
combined_raster = Rasters.combine(series, Ti) # this works, but takes a very long time
```
[Here](https://github.com/xKDR/raster-experiments/tree/main/DATA) is the data directory, if someone wants to repeat the experiment. The files are small. 

I used `@time` macro for testing the performance 
```
1475.228772 seconds (23.97 G allocations: 1.105 TiB, 7.06% gc time, 0.24% compilation time)
```
Reading an individual file from DATA takes only about 3 seconds, but combining them is slow.

**Comment by ayushpatnaikgit** [comment]
I tried: 

```julia
using Rasters
# the directory "DATA" contains the tif files
filelist = readdir(joinpath(pwd(), "DATA"), join = true)

Raster1 = Raster(filelist[1])
Raster1 = Raster(filelist[2])
@time cat(Raster1.data, Raster2.data, dims = 3)
```
```
872.387554 seconds (15.97 G allocations: 694.901 GiB, 9.66% gc time)
```

and 
```julia
@time cat(Array(Raster1.data), Array(Raster2.data), dims = 3)
```
```
6.322172 seconds (24.00 k allocations: 4.057 GiB, 4.16% gc time, 0.21% compilation time)
```

It's the same [DATA](https://github.com/xKDR/raster-experiments/tree/main/DATA) folder as above.

**Comment by rafaqz** [comment]
Try to update to the latest version v0.4.1, where this shouldn't happen.

But this is a lazy loading issue - somewhere we are reading each point in the array from disk individually, which is _very_ slow.
For more detail, lazy loading is implemented in https://github.com/meggart/DiskArrays.jl. The problem is DiskArrays.jl doesn't handle every single Base julia method yet, and it seems there is no fast method for `cat` (We have limited resources to make it 100% feature complete).

You can control lazy loading with the `lazy` keyword, which has recently been set to `false` by default:

```julia
series = RasterSeries(filelist, Ti(timestamps); lazy=true)
```

The solution in these circumstances (if you do need `lazy=true` at all) is to use `read`  which will read the data from disk (`Rasters.FileArray` object) to a regular `Array` if it is not already in memory: 

```julia
combine(read(series, Ti))
```

I hope this solves your problem, and thanks for the detailed issue.

**Comment by ayushpatnaikgit** [comment]
Thank you so much for the prompt response, Rafael. 
In version 0.4.1, the time taken for combining the series does come down to 6.9 seconds. 

Apologies for not trying this out before filing this issue. All my future experiments will be with the latest version.

**Comment by rafaqz** [comment]
No worries, always feel free to make issues its good feedback around how the package is being used.

**Comment by ayushpatnaikgit** [comment]
Hi Rafael, 
Now, for large datasets, it's going out of memory.
I am only interested in a small region. Could I crop before combining? Perhaps something like:

```julia
bounds = X(Rasters.Between(72.721252, 73.074187)), Y(Rasters.Between(18.849475, 19.49907))
series = RasterSeries(filelist, Ti(timestamps))
series = series[bounds...] # doesn't work
combined_raster = Rasters.combine(series, Ti) 
```

**Comment by rafaqz** [comment]
We cant select series by bounds like that, as the dimension of the series is time, not space.

Take the bounds of the contained `Raster`s instead using `map`. And to save memory, make the series `lazy=true`.
```julia
series = RasterSeries(filelist, Ti(timestamps); lazy=true)
cropped_series = map(series) do rast
    rast[bounds...] # should work how you want
end
combined_raster = Rasters.combine(cropped_series, Ti) 
```

This will still go out of memory if the bounded area is large.

It could be made to use at minimum half the memory when `cat` works in DiskArrays.jl (I will write that in the next few weeks hopefully), by using a `view` of `rast` to keep things lazy and making `cat` write directly from disk to the `combined_raster` parent `Array`. Currently doing that will hit the same bug you hit earlier.

A further option for _really_ large files is to pass in a `filename` argument to `combine` and write directly to disk, then this will work with any data size by streaming directly from lazy disk arrays to another disk array. I will implement this at some stage as well.

**Comment by ayushpatnaikgit** [comment]
I was able to solve this by doing

```julia
bounds = X(Rasters.Between(72.721252, 73.074187)), Y(Rasters.Between(18.849475, 19.49907))
cropped_raster_files = [Raster(i)[bounds...] for i in filelist]
series = RasterSeries(cropped_raster_files, Ti(timestamps))
combined_raster = Rasters.combine(series, Ti)
```

**Comment by rafaqz** [comment]
I think my method will be faster, as yours loads all the data. You can pass `lazy=true` to `Raster` to improve load time in your version.

**Comment by ayushpatnaikgit** [comment]
Thanks, I will try it out.

**Comment by ayushpatnaikgit** [comment]
@rafaqz yes, `lazy = true` makes it a lot faster. Thanks.
