### ISSUE TITLE
Dict() as metadata

### ISSUE THREAD

**Issue by ryofurue** [rafaqz/Rasters.jl#302]
It would be nice if `Dict()` could be used for a new set of metadata as `rebuild( . . . ; metadata=Dict())` and `RasterStack(. . . ; metadata=Dict())`.  Currently the new metadata as `Dict` doesn't get written to the netCDF file when `write("output.nc", stack)` and one has to use `Metadata(Rasters.NCDfile)` instead.

The following is not a *minimal* example. It's rather a typical use case. I need a set of metadata for each `Raster` as well as for the `RasterStack`.
```julia
using DimensionalData: Metadata
using Downloads
using Rasters

const NC_meta = Metadata{Rasters.NCDfile}

const url = "https://www.unidata.ucar.edu/software/netcdf/examples/sresa1b_ncar_ccsm3-example.nc"
infile = Downloads.download(url, "tmp.nc")
#infile = "tmp.nc"

ua = Raster(infile; name = "ua")
v = rebuild(similar(ua[:,:,1,1]); name=:v, metadata=NC_meta(:long_name => "sample"))
w = rebuild(similar(ua[1,:,:,1]); name=:w, metadata=NC_meta(:history => "hello"))
metadata(v)[:units] = "someunits"
metadata(w)[:units] = "otherunits"
#display(metadata(v))
s = RasterStack(v,w; metadata=NC_meta())
metadata(s)[:comments] = "global metadata"
write("tmp2.nc", s)
```

**Comment by rafaqz** [comment]
The reason to have the `Metadata` wrapper at all is so we know that the metadata came from a specific file type, and we can just write it directly, or need to convert some of the terminology to write to a different file type.

Most file types don't allow arbitrary metadata, either.

To generally write a `Dict` as metadata, we need to issue `@warning` on the file types it is ignored for, and list the specific fields that are allowed.

Even for netcdf, some fields like "units" have a specific list of allowed values that we should at least check and throw warnings for: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03.html.

**Comment by rafaqz** [comment]
This works now
