### ISSUE TITLE
The eltype of a raster with `missingval` = `missing` is not Union{Missing, ...}

### ISSUE THREAD

**Issue by ayushpatnaikgit** [rafaqz/Rasters.jl#307]
In the following example, a raster has `missingval` = `missing`, but eltype is Float32 instead of Union{Missing, Float32}
  
```julia
julia> dc = read(Raster("mumbai_radiance.nc"))
julia> dc 
84×155×1×123 Raster{Float32,4} unnamed with dimensions: 
  X Mapped Float64[72.7250001018, 72.72916676850001, …, 73.0666667712, 73.0708334379] ForwardOrdered Explicit Intervals crs: EPSG mappedcrs: EPSG,
  Y Mapped Float64[19.495832889299994, 19.491666222599996, …, 18.858332884200003, 18.8541662175] ReverseOrdered Explicit Intervals crs: EPSG mappedcrs: EPSG,
  Band Categorical Int64[1] ReverseOrdered,
  Ti Sampled Int64[201204, 201205, …, 202205, 202206] ForwardOrdered Irregular Points
with missingval: missing
[:, :, 1, 1]
 ⋮      ⋱  
[and 122 more slices...]

julia> eltype(dc)
Float32
```
Consequently, we cannot make a value = missing, as shown below. 
```julia
julia> dc[1,1,1,1] = Missing
ERROR: MethodError: Cannot `convert` an object of type Missing to an object of type Float32
```
`mumbai_radiance.nc` can be found [here.](https://github.com/ayushpatnaikgit/NighttimeLights.jl/blob/rasters/assets/mumbai_ntl/datacube/mumbai_radiance.nc) The file size is 6.4 MB. 

I have generated this .nc file by combining tif files that can be found [here](https://eogdata.mines.edu/nighttime_light/monthly/v10/). 

The code to generate the .nc file goes something like this. 
```julia
using Rasters
bounds = X(Rasters.Between(72.721252, 73.074187)), Y(Rasters.Between(18.849475, 19.49907))
mumbai_radiances = [Raster(i, lazy = true)[bounds...] for i in filelist]
series = RasterSeries(mumbai_radiances, Ti(timestamps)) 
combined_raster = Rasters.combine(series, Ti)
write("mumbai_radiance.nc", combined_raster)
```

Perhaps there can be a function to update the eltype, or by default whever the `missingval` is `missing`, the eltype should be Union{Missing, ....}

**Comment by rafaqz** [comment]
Ok in this case it seems NCDatasets.jl is returning an array without a `Missing` `Union` but we are assuming the missing value is `missing` because it usually is. It should be `nothing`, as in there are no missing values at all. Then `replace_misding` will work.

**Comment by rafaqz** [comment]
In the short term there is an easy hack to fix this:

```julia
rebuild(dc; missingval=nothing)
```

**Comment by ayushpatnaikgit** [comment]
Thanks, Rafael! 

I did the following
```julia
dc = rebuild(dc; missingval = nothing)
dc = replace_missing(dc, missing)
```
And now dc is `Union` `Missing`.

**Comment by rafaqz** [comment]
This is fixed on master now too.
