### ISSUE TITLE
Can't write Float16 data cubes

### ISSUE THREAD

**Issue by ayushpatnaikgit** [rafaqz/Rasters.jl#316]
Can't `write` a data cube which has Float16 values. 
```julia
raster = Raster("test.nc")
raster = Float16.(raster)
write("test.nc", raster) # doesn't work
```
```julia
ERROR: Your data is not a type that netcdf can store
```
While there are no issues if I convert it to Float32 and then write. 
```julia
raster = Float32.(raster)
write("test.nc", raster)  # this works
```
Also no issues if I convert it to Float64 and then write. 
```julia
raster = Float64.(raster)
write("test.nc", raster)  # this works
```
I used [this](https://github.com/xKDR/NighttimeLights.jl/blob/rasters/assets/mumbai_ntl/datacube/mumbai_radiance.nc) netCDF file for testing. It's called `mumbai_radiance.nc` instead of `test.nc`

**Comment by rafaqz** [comment]
NetCDF doesn't support `Float16`. But maybe we should sillently convert to `Float32`?

Xarray seemed to decide it was best to make the user do that manually:
https://github.com/pydata/xarray/issues/1877

But we could make the error message clearer?

**Comment by ayushpatnaikgit** [comment]
I also think that it's best for the user to convert it manually, and it can be suggested in the error message. Perhaps something like:  
```julia
if typeof(raster[1]) == Float16
@error "NetCDF doesn't support Float16, convert your variable Float32.  
```
