### ISSUE TITLE
`mosaic` to fail in the example

### ISSUE THREAD

**Issue by luraess** [rafaqz/Rasters.jl#341]
Trying to run the example from https://rafaqz.github.io/Rasters.jl/stable/, I am getting the attached error upon executing following step (in the https://rafaqz.github.io/Rasters.jl/stable/#Plotting section)
```julia
scandinavia = mosaic(first, denmark, norway, sweden)
```
The error is here [error.txt](https://github.com/rafaqz/Rasters.jl/files/10125265/error.txt)

```julia
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by rafaqz** [comment]
Is this the latest Rasters.jl and DimensionalData.jl?

**Comment by luraess** [comment]
It is
```julia
(tmp_rasters) pkg> st
Status `~/Desktop/tmp_rasters/Project.toml`
  [91a5bcdd] Plots v1.36.6
  [a3a2b9e3] Rasters v0.4.1
  [8e980c4a] Shapefile v0.8.0
```

**Comment by rafaqz** [comment]
Oh sorry I have forgotten to register the patch version for this. It should be working in half hour or so.

**Comment by luraess** [comment]
Thanks for your fast fix! That works fine now.
