### ISSUE TITLE
the function mask runs too slow

### ISSUE THREAD

**Issue by luoxxib** [rafaqz/Rasters.jl#379]
__I have added a _complete_ minimum working example below including downloads of any files required and understand that without it my bug is very hard to be fix__

```julia
mwe_here
```

__I have pasted a _complete_ error from function call down to the end__
```julia
error here
```

**Comment by rafaqz** [comment]
Can you see the template above? You need to fill it out or I can't know how to help you.

**Comment by luoxxib** [comment]
**python code:**

import rasterio
from rasterio.mask import mask
import geopandas as gpd
import numpy as np
from shapely.geometry import mapping
from time import  time

img = r"F:\data\sample.tif"
shapefile = gpd.read_file(r'F:\data\samples_rpj.shp')
geoms = shapefile.geometry.values 

t1 = time()
# extract the raster values within the polygon 
with rasterio.open(img) as src:
    band_count = src.count
    for index, geom in enumerate(geoms):
        feature = [mapping(geom)]
        # the mask function returns an array of the raster pixels within this feature
        out_image, out_transform = mask(src, feature, crop=True) 
t2 = time()
print("time：{:9.9}s".format(t2-t1)) 

run time is 0.727999926s
---------------------------------------------------------------------------------------------------------------
**julia code:**

using Rasters
using Shapefile
using BenchmarkTools

rsdata = Raster("F:\\data\\sample.tif")
sampleshape = Shapefile.Table("F:\\data\\samples_rpj.shp")

@time for row in sampleshape          
    geom = Shapefile.shape(row) 
    lable = row.Name            
    out_image = mask(rsdata; with=geom)
end

run time is 27.646416 seconds

**Comment by rafaqz** [comment]
Thanks for the MWE. Yeah that's super slow. What about the second time you run it?

Julias biggest flaw is compiling things (here Shapefile.jl and Rasters.jl methods) the first time you use them, so it can be fast when you run some long running process. That makes it look bad in these startup comparisons to python.

But it's great if you have to process a 1gb shaoefile To a high resolution raster.

Julia 1.9 has cached compilation, and when it's released I will put some work into making sure more things compile and the start-up is faster. But your example will likely never be faster than python.



But also, you are using `crop=true` in python so it's an unfair comparison. Although I guess I should add that keyword too.

**Comment by rafaqz** [comment]
If you link file downloads I will actually profile and solve your problem. The size and type of data will matter a lot so reading you code has a large degree of speculation.

How large are the shapes and how many? What size and resolution raster? With the files I can see that.

But without that, I will say, try using the `crop` function before `mask`, or `mask!` to avoid allocating the second array.

**Comment by rafaqz** [comment]
Did this work for you?
