### ISSUE TITLE
Equivalent of `coords` in GeoArrays.jl

### ISSUE THREAD

**Issue by Mikumikunisiteageru** [rafaqz/Rasters.jl#382]
Hello @rafaqz,

I am trying to substitute Rasters.jl for GeoArrays.jl in some old codes. However, I haven't found a function in Rasters.jl like `coords` (v0.6.0+) or `centercoords` (v0.5.1-) in GeoArrays.jl that returns the center coordinates of a certain grid cell (indexed or subscripted) in a raster. (I guess that it is not recommended to manipulate indices of grid cells in a `Raster`, but sometimes it is really useful.) Anyway, I write a rough function `coords_sub` for that purpose. Here is an example.

```julia
using RasterDataSources # 0.5.5
bio1 = getraster(WorldClim{BioClim}, res="10m")[1]

using GeoArrays # 0.7.13
geoarray = GeoArrays.read(bio1)
coords(geoarray, [1, 1], GeoArrays.Center())
	# [-179.91666666666666, 89.91666666666667]

using Rasters # 0.5.1
using .LookupArrays
raster = Raster(bio1)
center(dim, id::Integer) = shiftlocus(LookupArrays.Center(), dim)[id]
function coords_sub(raster::Raster, xy)
	x, y, _... = xy
	xx, yy, _... = raster.dims
	return [center(xx, x), center(yy, y)]
end
coords_ind(raster::Raster, idx::Integer) = 
	coords_sub(raster, CartesianIndices(raster)[idx].I)
coords_sub(raster, [1, 1])
	# [-179.91666666666669, 89.91666666666666]
coords_ind(raster, 1)
	# [-179.91666666666669, 89.91666666666666]
```

Now my question is: Is this safe? Is there a better implementation? 

And, do you think it will be good to provide such a function officially here or in DimensionalData.jl? Afterall, you have already something like `At`, `Near`, etc. there that does the inverse job.

**Comment by mauro3** [comment]
X-ref: https://rafaqz.github.io/DimensionalData.jl/stable/api/#Sampling and https://rafaqz.github.io/DimensionalData.jl/stable/api/#Loci

**Comment by rafaqz** [comment]
Do you actually want to just rebuild the raster with the shifted index? That seems easier to me.

I have an internal method in DD `maybeshiftlocus` that does this. It's actually used a lot in Rasters.jl to e.g. get the pixels of a plot to be in line with the ticks, or to standardise line burning algorithms in rasterization.

We could expose that to users?

"maybe" is because it does nothing if it's already correct, and "locus" is an obscure term, but I used it because the definition makes sense and `coord` is so overloaded in geo code.

**Comment by mauro3** [comment]
Side-question: Can `maybeshiftlocus` also be used to go from `Interval` to `Point` sampling?

**Comment by rafaqz** [comment]
Yeah I guess we need that too to make sure it's done properly? Points are usually converted to `Intervals` as if they have a `Center` locus, so that shift could be automated I guess.

**Comment by Mikumikunisiteageru** [comment]
Not actually, I guess I am not looking for an operation on a raster. What I want here is a function that an index/subscript goes in, and coordinates comes out.

If I am understanding correctly, a `Raster` is essentially an array with many other properties. As an array, its elements can be subscripted. For example, we can talk about the element at the 1st row, 1st column --- subscripted by `(1, 1)`. The element represents the value of a rectangular tile somewhere in the coordinate system. In this case (WorldClim, 10 minute resolution), the tile expands from -179.833 to -180 on X and from 89.833 to 90 on Y, so the center of the tile is located at `(-179.917, 89.917)`. 

Now I am finding an elegant way to map `(1, 1)` to `(-179.917, 89.917)` and also map other possible subscripts to corresponding tile center coordinates. Could you please give me some advice?

**Comment by Mikumikunisiteageru** [comment]
By the way, is it possible for Rasters.jl to represent a slant grid? For example, one axis from NE to SW and the other from NW to SE.

**Comment by rafaqz** [comment]
Slant grid will load and plot with a coordinate transform. Not all the functions and selectors work on that though, it's some work to do that. Like you can't rasterize to that as it would need a separate function and would be slow.

**Comment by rafaqz** [comment]
For the index in, coordinate out there is `DimPoints` from DimensionalData.jl.

It's a lazy AbstractArray over dimensions. Index it and get points back.

Use `maybeshiftindex` first to change the positions.

**Comment by mauro3** [comment]
And whilst were at it: what's the inverse of DimPoints?  I.e. I got the coordinates and want the indices.  This works:
`CartesianIndex(findfirst(dims(raster)[1].==xcoord, findfirst(dims(raster)[2].==ycoord))` but there is probably something better.

**Comment by rafaqz** [comment]
`dims2indices` will do that if you use At or Near selectors.

**Comment by mauro3** [comment]
Like so `IJ = CartesianIndex(dims2indices.(dims(raster), [X(At(xcoord)), Y(At(ycoord))])...)`.  I guess a `DimPoints`-like interface could be nice.

**Comment by Mikumikunisiteageru** [comment]
`DimPoints` is exactly what I am looking for. Thanks!

I agree that it will be more convenient to have an implicit `maybeshiftlocus` during the construction procedure of a `DimPoints`. 

Also another thing that can be further improved: when I tried to construct the `DimPoints` for a 2160×1080×1 `Raster` and `display` it on REPL, digits flooded on the screen. Maybe it is better to simplify the way such a type is shown.

**Comment by rafaqz** [comment]
Yeah, `DimPoints` needs a show method. Would be a nice PR if you have time, you ca copy the style of the other show methods.

For the `maybeshiftlocus` behaviour, I can add a `locus` keyword to `DimPoints` that defaults to `nothing` - meaning don't change anything. But if you pass in `Start` , `End` or `Center` it will run `maybeshiftlocus`. We could also break it into dims, like `locus=(X(Center()), Y(Start()))` but maybe thats not really needed.

**Comment by Mikumikunisiteageru** [comment]
I think the former task is easier for me. I will have a try later.
