### ISSUE TITLE
Split-apply-combine on rasterlayers

### ISSUE THREAD

**Issue by tiemvanderdeure** [rafaqz/Rasters.jl#396]
The only way to split-apply-combine on rasterslayers right now is to loop over views, apply the function, and concatenate the resulting rasters. It could be useful to have a function that does this.

A typical example use case would be generating monthly values from a time series in one command.

In the R package terra this functionality is implemented in the tapp function: https://rdrr.io/cran/terra/man/tapp.html

**Comment by rafaqz** [comment]
We have `groupby` in DimensionalData now
