### ISSUE TITLE
Can not set output bounds with `resample`

### ISSUE THREAD

**Issue by stefanomoro** [rafaqz/Rasters.jl#399]
I have to resample a DEM file to UTM, having as input a coordinate `(lat,lon)` that is the center of the output raster. 
I also know the desired dimension in pixels of the output. 
With Python, I used GDAL to convert the `lat/lon` to the `x/y` of the UTM projection and then used `gdal.Warp()` to resample the DEM to the desired projection, setting the desired output bounds as UTM coordinates.

With Rasters.jl I can use the `warp` function for this resampling with these parameters:
```
A = Raster(dem_file)
flags = Dict(
    :t_srs => convert(String, convert(WellKnownText,EPSG(32611))),
    :te => output_bounds,
    :te_srs => convert(String, convert(WellKnownText,EPSG(32611))),
    :tr => [pixel_spacing_in_m, pixel_spacing_in_m],
    :r => :cubic
)
B = warp(A, flags)
``` 
where `output_bounds` is a 4 elements Vector defined as `[x_min y_min x_max y_max]`,  referring to the UTM CRS .

If I wanted to use `resample()` instead, I can not set the output bounds. So I have to resample all the DEM and then cut it with `output_bounds`. But it takes forever and I think it is not the best approach.  
This is how I used `resample`:
```
B = resample(A , pixel_spacing_in_m; crs = EPSG(32611), method = :cubic)
```

**Comment by rafaqz** [comment]
Thanks for the issue. 

`resample` is from before Extents.jl existed, so it only snaps to another `Raster` (`to` keyword). But we can make it the same as masking and rasterization where `to` can be an `Extent`, and have `res` as a keyword.
