### ISSUE TITLE
rplot! should be deleted or fully implemented in the Makie extension

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#402]
The rplot! function is not overloaded in the Makie extension, therefore it is confusing to have it around in the Rasters namespace. 

Is it planned to have a rplot! function available or should one first plot the raster elements and then plot on top of the axes that rplot generated?

**Comment by rafaqz** [comment]
@asinghvi17 ?

**Comment by asinghvi17** [comment]
Looking at the code, I think that I'd intended to make it a part of the API which would add a colorbar, but figured it was better to wait for figure level recipes for that. 

We could probably remove it.  @felixcremer, the best way to do this is probably to plot the raster elements first, then plot on top of the axes as you mentioned.  Of course that's only if you want to use `rplot` - `plot` works fine with Rasters as well, if you only want to plot to a single axis.

**Comment by asinghvi17** [comment]
Should be closed now
