### ISSUE TITLE
Feature request: dont check `isfile` for http sources

### ISSUE THREAD

**Issue by ryofurue** [rafaqz/Rasters.jl#406]
Since the netCDF library has a builtin capability of lazily reading data from an OPeNDAP server, it would be nice if we can create a `Raster` by something like this:
```julia
using Rasters
url = "http://apdrc.soest.hawaii.edu:80/dods/public_data/" *
  "WOA/WOA18/5_deg/monthly/temp"
varname = "tmn"
rs = Raster(url; name = varname, dataformat=:netcdf)
```
Rafael Schouten said in [Julia discourse](https://discourse.julialang.org/t/create-a-raster-from-opendap-netcdf/96756/2):
> The first problem is there is no way to tell this is a NetCDF and you should use the NCDatasets.jl backend, as there is no .nc extension. So you need to use source=Rasters.NCDfile.
> But then there is a check for if the file exists, and of course that fails.
> What we should do is skip file checks if the path starts with `http` and similar.

But,  in the future, there may be other data formats that use the HTTP protocol to represent remote data.  So, wouldn't an optional argument such as `dataformat=:netcdf` be more extensible? 

Also, that would help this situation:
```julia
rs = Raster("tmp.cdf"; name = "slp", dataformat=:netcdf)
```
There are still ancient netCDF files around that use the old extension `.cdf`.

**Comment by rafaqz** [comment]
Hmm `:daraformat=:netcdf` is strictly less  extensibly than what we have, because you cant dispatch on symbol.

Now you can do `source=Rasters.NCDfile`, or `GDALfile`, etc.

Do you actually mean that its nicer to type?

**Comment by ryofurue** [comment]
> Now you can do source=Rasters.NCDfile, or GDALfile, etc.
> Do you actually mean that its nicer to type?

No, I don't.   From the user's point of view, `"netcdf"` or `:netcdf` or similar would be ideal.  So, I think "NCDfile" would be fine but "Rasters.NCDfile" wouldn't.

But, would it be possible to use a table that maps `dataformat`s to `source`s?
```julia
   # Pseudo code!  Don't take it literally.
   # I'm not suggesting `dataformat` is a good name.
   # It's just a placeholder.
   function Raster(filename, . . . ; dataformat, . . . )
      . . . . 
     return createRaster(filename; source=sourcetable[dataformat])
   end
```
Then you could use nice names like "netcdf", "gdal", etc. as `dataformat`. 

It's like the `open` statement of Fortran.  `Open`  wouldn't try to detect the format from the filename. The user gives format information to `open`.

**Comment by ryofurue** [comment]
By the way, defaulting to netCDF for the "http" prefix may be a fine solution.  Perhaps its' unlikely that other file formats also use the HTTP protocol.  For example, *if I understand correctly*, GDAL seems to use a "virtual file system"

https://gdal.org/user/virtual_file_systems.html

to distinguish various remote data types.  In this case, the prefix "/vsizip/" will tell that it's a GDAL file.  

Also, I've seen that the "s3" protocol is used.  In this case, I don't know whether "s3://" is sufficient to tell the format or not.

Anyway, perhaps it's only netCDF that uses "http" to represent a remote dataset.

**Comment by rafaqz** [comment]
For gdal we add the vsi automatically, users dont have to add it. So we cant assume http is a netcdf.

But I get your point about nicer names to specify, we can map `:gdal => GDALfile` and `:netcdf => NCDfile`.
