### ISSUE TITLE
Help: Is there a way to get cellsize

### ISSUE THREAD

**Issue by shy86** [rafaqz/Rasters.jl#415]
Hello, 

I am new to this package and have been using R before.

In some calculations of grid cells area weighting, I need to extract the grid area. In the previous R package `terra` (`raster`) provides `cellsize` (`area`) function. Is it possible to have a similar implementation in the `rasters` package?

**Comment by shy86** [comment]
Thanks for your answer.

Yes, output units are necessary. In fact, this could be a very useful function. I'm not particularly familiar with the julia language, and I've currently written a very simple version that just uses the sine function of latitude, which may not be accurate or what you want. 

After I get familiar with the Julia language, I may try to write this function and PR, but this may take longer.

I really hope that this feature can be added. Thank you very much for your work.

**Comment by rafaqz** [comment]
It can totally be aded, but its always a question of available time. I do a PhD full time and work on many other packages.

In open source things move fastest when the person that needs something the most writes the PR!

And you need this the most and actually know what is required, so youre well ahead of me already.

**Comment by tiemvanderdeure** [comment]
This functionality has been added in #508
