### ISSUE TITLE
What are the expected input for the CRS?

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#417]
The setcrs and the setmappedcrs docstrings do not specify what is the type of the crs input.
Do I understand correctly, that these are supposed to be a GeoFormatTypes object?

The same is true for the crs and mappedcrs keyword in the Raster docstring.

If the expected type is a GeoFormatTypes I would be happy to provide a PR to fix these docstrings.

**Comment by rafaqz** [comment]
Yes - GeoFormatTypes `CRS` or `Mixed` `GeoFormat`

A better docstring would be great
