### ISSUE TITLE
[Help wanted] Add dimension

### ISSUE THREAD

**Issue by ThomasAuriel** [rafaqz/Rasters.jl#453]
I would like to add a dimension to a raster object.

Currently i do this:
```julia
# Get a subset of the initial ds raster object
subDs = ds[Ti=At(time)]
# Add the time dimension to keep the time dimension
subDs = rebuild(subDs; dims=(subDs.dims..., Ti(time)))
```

Today, this code give me this error:
```
Internal Error: BoundsError: attempt to access Tuple{} at index [1]
```

(dims has the X and Y dimensions)

- Is it possible to keep the dimension when I retrieve a sub dataset ?
- Is it possible to add a dimension ?

**Comment by rafaqz** [comment]
You would need to add a dimension to the array at the same time or it wont match? `rebuild` is not fancy, it just uses what you give it.

But why no instead index with a range or vector:

```julua
subDs = ds[Ti=At([time])]
```

Then you wont lose the dimrnsion

**Comment by ThomasAuriel** [comment]
Oh ! That's clever. I hadn't thought of that. It works as expected. Thank you.

For the second question:
Let's say later in my code I need to add a dimension, how could I do ?

Does RasterStack could be the solution ?

**Comment by rafaqz** [comment]
Yeah its a little harder...

With a base `Array` you can just add colons to indexing:

```julia
julia> zeros(2, 2)[:, :, :]
2×2×1 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0
 0.0  0.0
```

But here you also want to add a dimension. This should work fine if your array is a matrix: 

```julia
subDs = rebuild(subDs[:, :, :]; dims=(dims(subDs..., Ti(time)))
```

Its not a very common thing to do, so I'm not sure if it needs a function in DD.
