### ISSUE TITLE
writing to netcdf changes dimensions and can result in ArgumentError

### ISSUE THREAD

**Issue by tiemvanderdeure** [rafaqz/Rasters.jl#461]
I have a Raster with regular mapped Intervals on each axis in a tif file.

When writing this Raster to a netcdf and loading it back in, the points look different and I sometimes get an error when filtering using Contains().

This also works when just generating a Raster myself like so:

```
using DimensionalData.LookupArrays, Rasters

xlen = 801
ylen = 1001
x = X(Projected(LinRange{Float64}(-20.05, 59.95, xlen), crs = EPSG(4326), mappedcrs = EPSG(4326), sampling = Intervals(Start())))
y = Y(Projected(LinRange{Float64}(59.95, -40.05, ylen), crs = EPSG(4326), mappedcrs = EPSG(4326), sampling = Intervals(Start())))

my_raster = ones(x, y)

write("my_raster.nc", my_raster)

raster_from_nc = Raster("my_raster.nc")

raster_from_nc[Y = Contains(7.35)] # ArgumentError: No interval contains 7.35

my_raster[Y = Contains(7.35)] # just to check 7.35 should be there
```

I can't find much of a pattern in which values throw an error and which don't. 7.15, 7.25, and 7.45 don't, but 7.55 does.

Writing to .tif does not give the same problem.

**Comment by rafaqz** [comment]
Should be working on Rasters 0.8.1 and DD 0.24.14
