### ISSUE TITLE
Constructing Rasters Fails on 0.8.0

### ISSUE THREAD

**Issue by JoshuaBillson** [rafaqz/Rasters.jl#463]
It seems that I'm unable to construct a Raster in the latest version of Rasters.jl (0.8.0).

Here is a working example:

```julia
using Fetch, Rasters

link = "https://drive.google.com/file/d/15CPQ4R5XQeIeCKcxkLFkMVBgrSkre4kt/view?usp=sharing"

gdownload(link, pwd())

Raster(joinpath(pwd(), "LC08_L1TP_043024_20200802_20200802_01_RT_B4.TIF"))
```

And this is the error output when executing the last line in the above code:

```julia
ERROR: Run `import ArchGDAL` to read /Users/jmbillson/Julia/rastertest/LC08_L1TP_043024_20200802_20200802_01_RT_B4.TIF
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] _open(f::Function, T::Type, filename::String; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/sources/sources.jl:62
 [3] _open(f::Function, T::Type, filename::String)
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/sources/sources.jl:60
 [4] #_open#186
   @ ~/.julia/packages/Rasters/IELXJ/src/sources/sources.jl:58 [inlined]
 [5] _open
   @ ~/.julia/packages/Rasters/IELXJ/src/sources/sources.jl:57 [inlined]
 [6] #Raster#52
   @ ~/.julia/packages/Rasters/IELXJ/src/array.jl:303 [inlined]
 [7] Raster(filename::String)
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/array.jl:299
 [8] top-level scope
   @ REPL[4]:1
```

**Comment by JoshuaBillson** [comment]
Yes, I read the error. I assumed that `Rasters ~/.julia/packages/Rasters/IELXJ/src/array.jl:299` meant that `array.jl:299` was executing a method which relies on `ArchGDAL` but it was not imported by Rasters.jl. Thus, I assumed the fix was to import ArchGDAL on our end. It is not at all obvious that `Run import ArchGDAL` was a message intended for the end user.

Would it be possible to have a more useful error message given the move to extensions? I think this is going to confuse a lot of users unless we get ahead of it.

Also, while I now see that the docs have been updated to reflect this change, it is not immediately apparent unless one is specifically looking for it. Perhaps we could add information boxes to draw the user's attention to this change, as was done in [FluxML](https://fluxml.ai/Flux.jl/stable/training/training/) when they introduced explicit gradients. I'd be happy to modify the docs accordingly if there's an appropriate fork for me to work on. Otherwise, I could create a new fork from `main`.

**Comment by rafaqz** [comment]
Yeah thats just a random thing I wrote, sorry its not clearer. Julia 1.9 does not provide a canonical error for loading extension packages so we are all just making somerhing up.

If you have something better please PR!

Its good to understand this package as a part time project of someone doing a PhD and maintaining 40+ other packages. Things like this are unlikely to be polished and any input you have is very valuable, but best made through PRs that improve things directly.

**Comment by rafaqz** [comment]
I will try to get a PR into base with a standard error message for this.

**Comment by JoshuaBillson** [comment]
I've opened a [PR](https://github.com/rafaqz/Rasters.jl/pull/465) with the updated error message.
