### ISSUE TITLE
Access to RasterDataSources could give error that indicates that ArchGDAL needs to be loaded in 0.8

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#468]
In Rasters 0.8 I get the following error, when I try to load a file from RasterDataSources:

```julia
julia> A = Raster(WorldClim{BioClim}, 5)
ERROR: MethodError: no method matching Raster(::Type{WorldClim{BioClim}}, ::Int64)

Closest candidates are:
  Raster(::Any, ::Tuple; name, kw...)
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/array.jl:282
  Raster(::Any, ::AbstractString)
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/array.jl:308
  Raster(::Any, ::AbstractString, ::Any; crs, mappedcrs, dims, refdims, name, metadata, missingval, source, write, lazy, dropband)
   @ Rasters ~/.julia/packages/Rasters/IELXJ/src/array.jl:308

Stacktrace:
 [1] top-level scope
   @ REPL[151]:1
```

This is working in 0.7.

**Comment by felixcremer** [comment]
Ok, this is only broken when I haven't loaded ArchGDAL, but it would be nice to get a error message indicating that I need to load ArchGDAL.

**Comment by rafaqz** [comment]
It should need both RasterDataSoirces and ArchGDAL.

But to make a better error, its not easy to get at that method using dispatch without having the supertypes avalable. Its also not clear from the signature if you need ArchGDAL or NCDatasets.

If you can work out how to do it a PR would be nice.

**Comment by rafaqz** [comment]
This is implemented now
