### ISSUE TITLE
Write test for calling RasterSeries(x; duplicate_first=true)

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#474]
We should write a test for calling `RasterSeries(x; duplicate_first=true)` and check that it a) works and b) correctly sets the properties, especially the filenames. I think this requires some usable sample data uploaded somewhere. I could provide the sample data if needed; where could it be uploaded?

**Comment by rafaqz** [comment]
We van also just generate the data in the tests.

**Comment by maxfreu** [comment]
# create `N` random rasters with eltype `type` and x,y,band size `size`
function temporary_random_rasters(f, N, size, type=UInt8)
    filenames = [tempname() * ".tif" for _ in 1:N]
    try
        for f in filenames
            write(f, Raster(rand(type, size); dims=(X(1:size[1]), Y(1:size[2]), Band(1:size[3]))))
        end
        f(filenames)
    finally
        rm.(filenames; force=true)
    end
end


temporary_random_rasters(3, (10,10,3), UInt8) do filenames
    times = Ti(DateTime.(rand(UInt16, length(filenames))))
    series = RasterSeries(filenames, times; duplicate_first=true)
    ...
end
