### ISSUE TITLE
Trying to `combine`multiple lazy loaded files kills julia

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#481]
When I try to combine multiple large files that are loaded lazily into a RasterSeries into a new Raster this kills my Julia process.
I suspect, that the views load all the data from disk into RAM and that gets Julia killed with OOM. 
Could we have a lazy version of combine so that only the metadata is handled and the data will be loaded later when it is actually needed?

I will post a MWE that breaks my julia process tomorrow.

**Comment by rafaqz** [comment]
I have a PR to DiskArrays that adds lazy `cat`, which should be a solution to this?

 If you want to review it ;)

**Comment by rafaqz** [comment]
This should be fixed now, we use `DiskArrays.ConcatDiskArray` in `combine`.
