### ISSUE TITLE
Link broken in README.md

### ISSUE THREAD

**Issue by tomchor** [rafaqz/Rasters.jl#496]
There seems to be a broken link in the README:

![image](https://github.com/rafaqz/Rasters.jl/assets/13205162/b5c95ea4-a0b9-4f68-83bd-5e11d8a65a1d)

This is the link:

https://github.com/rafaqz/Rasters.jl/blob/9cd75f6e5b25194021764fdb6f2f54dfd590b9ef/README.md?plain=1#L15

**Comment by rafaqz** [comment]
Oh its from the docs update. We just need to find the new content lunk from the docs and update the readme.

**Comment by lazarusA** [comment]
I want to update also the plot, and include the code in the same place. I will try to do later today.

**Comment by tomchor** [comment]
This can be closed already, no?

**Comment by tomchor** [comment]
Actually it turns out the same link is still broken in the docs:

![image](https://github.com/rafaqz/Rasters.jl/assets/13205162/bb2b9cb1-5ce2-41ea-948f-00198b9dfc86)

Maybe reopen this until that's fixed?

**Comment by lazarusA** [comment]
the latest version is at https://rafaqz.github.io/Rasters.jl/dev/, where things are not broken and up to date.

**Comment by tomchor** [comment]
Ah I see. The docs weren't deployed yet.
