### ISSUE TITLE
SLC Incorrect Data on Write

### ISSUE THREAD

**Issue by joshday** [rafaqz/Rasters.jl#502]
I have a [Single Look Complex](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-1-sar/products-algorithms/level-1-algorithms/single-look-complex) .tiff file where the underlying data changes on a read-write-read roundtrip.

Data found on https://search.asf.alaska.edu/ (S1A_IW_SLC__1SDV_20230103T230613_20230103T230641_046626_059699_9E8C)

```Julia
julia> slc = Raster(path);

julia> Rasters.write("test.tiff", slc; force=true)
"test.tiff"

julia> slc2 = Raster(ans);

# data from the "read" matrix and the "read-write-read" matrix are different
julia> slc.data == slc2.data
false

# The errors sum to zero.  An incorrect transpose?
julia> sum(x - y for (x,y) in zip(slc.data, slc2.data))
0 + 0im

julia> mean(abs(x - y) for (x,y) in zip(slc.data, slc2.data))
73.42267370323304
```

A likely related issue is that the written file is about half the size as the original:

```Julia
julia> filesize(path)
1186109408

julia> filesize("test.tiff")
673542244
```

---

I'll look into this further and add more details as I find them.  Just wanted to get an issue in writing.

**Comment by rafaqz** [comment]
Sounds BAD. Will try to fix. But can you download the file inline in your MWE? 

Otherwise a big chunk of my available bugfix time dissapears looking for demo rasters on various platforms, rather than fixing bugs ;)

**Comment by joshday** [comment]
I know it's really annoying to reproduce...I don't think they have an API though.  They require an account and all the files are > 1Gb.  

My hunch is that is has to do with rotations, but I'll try to get a simpler MWE tomorrow

**Comment by rafaqz** [comment]
I just couldnt find the file after 5 mins looking a gave up 😂

**Comment by joshday** [comment]
Okay, so looks like an axis gets flipped.  Here's the original and roundtrip data heatmaps side by side:

<img width="575" alt="Screenshot 2023-08-24 at 10 43 37 AM" src="https://github.com/rafaqz/Rasters.jl/assets/8075494/1da4889b-e3a9-4fd1-8063-e09909c31981">

**Comment by rafaqz** [comment]
I found a file matching that name on there but it won't even load in GDAL so I'm not sure what you're actually doing - I really need a full MWE here

**Comment by rafaqz** [comment]
Ok, this is kind of minor problem really. By convention non rotated geotiffs are usually stored with the Y axis flipped, or "north up". So users don't have to do this reversing manually all the time we do it automatically. I guess if there is any kind of rotation we should'nt do that.

This is pretty well explained in this stackexchange
https://gis.stackexchange.com/questions/122647/do-rasters-other-than-north-up-exist-in-the-wild
