### ISSUE TITLE
Turn off threading for rasterizing really large rasters

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/Rasters.jl#532]
Because we need to make separate rasters for each thread to write to, threading can use all RAM when a single thread would still work.

We should look at how to check available memory and raster size and use some heuristic. 

See #529

**Comment by alex-s-gardner** [comment]
One option would be to thread by tiles, cropping the shapes to each tile would also greatly reduce the search space... though I suspect this would be a more involved mod.

**Comment by rafaqz** [comment]
Cropping the shapes may take longer than rasterizing them unfortunately. 

And if there are just a few big polygons then the tiles are broken.

I suspect the key problem is actually that I switched the burning arrays from BitArray to Array{Bool} and that means 8x more memory. Maybe we can just swap that back and keep the threading in most cases... it only doubles the memory use for UInt8 arrays and 8 cores.
