### ISSUE TITLE
Method links to `resample` and `warp` are broken 

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#537]
links to `resample` and `warp` are broken:
https://rafaqz.github.io/Rasters.jl/stable/scripts/generated/basics/methods/

Also warp and resample to to appear in the API list which I believe they should

**Comment by rafaqz** [comment]
I think the problem is they are not in the docs at all, after splitting them out into the ArchGDAL extension.

Maybe we need to move all the docstrings into Rasters.jl proper as they are not being found in the extentsion?
