### ISSUE TITLE
how to tell Raster my tiff is a Center coordinate

### ISSUE THREAD

**Issue by kongdd** [rafaqz/Rasters.jl#556]
https://github.com/rafaqz/Rasters.jl/blob/8f95f8acd926a78fa285695c5242182c01055c54/test/sources/gdal.jl#L179-L183

I found a solution at here.
Just wondering whether there is a more simple way?

**Comment by rafaqz** [comment]
I should really make it print in `show`

You need to do `using Rasters.LookupArrays` 

Then its:
```julia
locus(dims(rast), X)
```

Als o been meaning to make this and other things a bit easier, just havent got around to it yet.

**Comment by rafaqz** [comment]
Fixed in DD, you can see this directly in the REPL now

**Comment by kongdd** [comment]
Thank you.
