### ISSUE TITLE
Axes in rplot should be linked 

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#560]
I would have expected that the Axis in the rplot would be linked, so that zooming into one also zooms into all the others.
It might be good to be able to set this with a keyword argument if this is not the behaviour that one would like to have depending on the data.

**Comment by rafaqz** [comment]
PR?

**Comment by felixcremer** [comment]
I looked into the code and realized that there are already some linkaxes calls and I can't reproduce it anymore that it is not linked. I will reopen it, when I find an example dataset, where the axes are not linked.
