### ISSUE TITLE
How do I write a RasterStack object to a GeoTIFF file using the Rasters package?

### ISSUE THREAD

**Issue by Ujjwal4CULS** [rafaqz/Rasters.jl#570]
I want to create a GeoTIFF file with a screenshot of the 'rasstack' variable. Can someone assist with this?
![gmmp](https://github.com/rafaqz/Rasters.jl/assets/28214594/0c883f15-30d7-4dd6-a9a5-30431ddc3936)

**Comment by rafaqz** [comment]
Is there a reason to use `RasterStack` specifically here? This is easier using `RasterSeries` as what you have is a series of rasters of identical size and type along a time dimension. 

Something like this should work:

```julia
using Rasters, ArchGDAL
# a RasterSeries can be created from the list of files
series = RasterSeries(tif_filenames, Band(basename.(tiff_filenames))
# combine turns the slices of a RasterSeries into a single Raster we can write as one file.=
raster = Rasters.combine(series, Band)
# Now we can write the geotiff
write("output_filename.tif", raster) 
```

Although I can test it without a MWE.

**Comment by rafaqz** [comment]
Closed due to lack of reply from Op, not clear what to add here.
