### ISSUE TITLE
How can one convert a DataFrames into a raster without knowing the resolution and extent?

### ISSUE THREAD

**Issue by Ujjwal4CULS** [rafaqz/Rasters.jl#572]
Could someone please assist in converting the attached data into a raster format, given that the resolution and extent are unknown?
![mo](https://github.com/rafaqz/Rasters.jl/assets/28214594/a0e5ef42-a2b1-4ae3-a3fc-4d27692e1415)

**Comment by rafaqz** [comment]
Looks like you want `rasterize`. Check the docs for usage. At minimum you need to define the resolution manually with the `res` keyword as its not always easy to guess something sensible. But the extent can be detected from the points.

The easiest way to do it is to combine your `Latitude` and `Longitude` columns into the GeoInterface.jl standard "geometry" column, as a tuple - which is recognised as a point.

Something like this should work:

```julia
df.geometry = collect(zip(df.Longitude, df.Latitude)))
rasterize(sum, df; res=your_res, crs=your_crs)
```

Its not so well documented but you could also just do:

```julia
rasterize(sum, df; res=your_res, crs=your_crs, geomcolumn=(:Longitude, :Latitude))
```

You can also specify `size` instead of `res` if that's easier. Also, you could use e.g. `maximum` instead of `sum` if you expect multiple points in each pixel. If there is never multiple points per pixel it will make no difference.

**Comment by Ujjwal4CULS** [comment]
Hi,

Thank you very much for your reply. However, I don't have the resolution and size of the data in this case. How can I perform the above code without this information?

**Comment by rafaqz** [comment]
Maybe you can write an algorithm to guess a resolution from the spacing of the points?

Is it originally coming from a square raster or just a scatter? I have not idea what this data is.

**Comment by Ujjwal4CULS** [comment]
The data comes from a square raster with a 300-meter resolution. This data was generated from the Sentinel-3 Water (Full Resolution) dataset.

**Comment by Ujjwal4CULS** [comment]
The error from your code is attached here as a screenshot.
![m01](https://github.com/rafaqz/Rasters.jl/assets/28214594/155446cb-374c-4e1e-a149-489f0919a1cf)

**Comment by Ujjwal4CULS** [comment]
I am providing a minimal example dataset and accompanying code for your review. This should help in investigating the issue at hand.  Additionally, the dataset (gt_dt.arrow) is available via the provided link [.](https://drive.google.com/drive/folders/1CskJh40kz9oYMCw6X7R3Dr-X8U9wOlXn?usp=sharing)

Here is a snippet of the code with error:
`using ArchGDAL, RasterDataSources, GeoData, HDF5, DataTables, DataFramesMeta, Makie, GeoMakie, GDAL, GDAL_jll, GeoArrays, Arrow, DataFrames, NCDatasets, Statistics, CairoMakie, GeoStats, GeoStatsBase

arrow_table = Arrow.Table("gt_dt.arrow")
reordered_df = DataFrame(arrow_table)
reordered_df.geometry = collect(zip(reordered_df.lon, reordered_df.lat))
dt_ras = Rasters.rasterize(sum, reordered_df; res=0.1000005, crs=EPSG(4326))
`
ERROR: UndefKeywordError: keyword argument `to` not assigned
Stacktrace:
 [1] top-level scope
   @ none:1

**Comment by rafaqz** [comment]
First, I'm wondering if you have an old version of Rasters.jl? thats not the error I get. 

What is actually missing is the `fill` keyword! - we need to specify using the `:value` column in your dataframe as our `fill` value. So:

```juliae
using Rasters, Arrow, ArchGDAL, DataFrames
arrow_table = Arrow.Table("/home/raf/Downloads/gt_dt.arrow")
reordered_df = DataFrame(arrow_table)
reordered_df.geometry = collect(zip(reordered_df.lon, reordered_df.lat))
dt_ras = Rasters.rasterize(sum, reordered_df; res=0.1000005, crs=EPSG(4326), fill=:value)
```

You can plot with Makie to verify:
```julia
using GLMakie
p = plot(dt_ras)
```
![plot](https://github.com/rafaqz/Rasters.jl/assets/2534009/1bc0bf96-54c8-4615-9b06-ad9e002d8c72)

**Comment by rafaqz** [comment]
And make sure that `sum` is the aggregation that you actually want before using this. Any reducing function will work.

**Comment by Ujjwal4CULS** [comment]
Could you please update this for the newer version of Rasters? I am unable to access or install the older version of Rasters. Does this line dt_ras = Rasters.rasterize(sum, reordered_df; res=0.1000005, crs=EPSG(4326), fill=:value) generate a 255-band raster stack data?

**Comment by rafaqz** [comment]
This worked for me both in `Rasters@0.9.0` and on `Rasters#main`

What is the output of `] status Rasters` for you?

**Comment by rafaqz** [comment]
On an older version Rasters did not automatically generate the axes using `res` or `size`, you had to pass them in using `to`.

**Comment by Ujjwal4CULS** [comment]
![test](https://github.com/rafaqz/Rasters.jl/assets/28214594/9155ed84-393e-40f4-bfc1-ffa80a676019)
I think it's an issue with the package update, isn't it?

**Comment by Ujjwal4CULS** [comment]
I think I am still getting the same error after the update.
![jl_2](https://github.com/rafaqz/Rasters.jl/assets/28214594/be5b137c-e249-4d6e-bb31-136a2c81d2b4)

**Comment by rafaqz** [comment]
Did you restart?

**Comment by Ujjwal4CULS** [comment]
After restarting, I still encountered the same error.

**Comment by rafaqz** [comment]
Did you activate the environment again?

**Comment by Ujjwal4CULS** [comment]
Thank you! Now it is working following your suggestion, but it generates a single-band raster. It should be a raster stack with 255 bands, and each band name should be a date. In this context, could you please tell me how to generate the raster stack data using my given data?

**Comment by rafaqz** [comment]
You will need to manually group your data using DataFrames.jl by date, and rasterize each group and make a vector of all of them. I can't teach you how to do this.

Then, concatenate all the rasters together on a `Band` dimension like `cat(rasters_vec...; dims=Band)` should work. Then you can `write(filename, concat_rasters)` to a geotiff.

**Comment by Ujjwal4CULS** [comment]
Thank you very much. Your suggestion is working for the RasterStack data.

**Comment by rafaqz** [comment]
You cant just try random commands ;)

When you make the Band dimension in `cat` you can do `...; dims=Band(your_names_vector))`

**Comment by Ujjwal4CULS** [comment]
Thank you very much for your reply. How can I set the names of the bands in a stacked .tif file?

**Comment by rafaqz** [comment]
`new_g = set(g, Band => your_band_names)`

**Comment by Ujjwal4CULS** [comment]
Thank you very much!

**Comment by rafaqz** [comment]
`DataFrame(rasterstack)` ;)

**Comment by Ujjwal4CULS** [comment]
The code provided above only generates values for rows*columns. My question is whether the DataFrame will create columns for x, y, band names, and values, akin to the terra package's as.data.frame(s, xy=TRUE) function in R?

**Comment by rafaqz** [comment]
Yes, that exactly what it outputs?

**Comment by rafaqz** [comment]
Again you must have ancient versions if something to get that result. Please check you are using new packages

**Comment by Ujjwal4CULS** [comment]
Your suggestion is working. Thanks for this discussion. I hope this will be helpful for many people, including myself and those who love Julia's performance in comparison to R and Python.
