### ISSUE TITLE
Export `extent` and show resolution if it is available.

### ISSUE THREAD

**Issue by Jigyasu4indp** [rafaqz/Rasters.jl#574]
I am sorry, I did not find well-documented information on the Rasters package. Could you please let me know how to view the resolution, extent, and projection of a Raster or RasterStack .tif file?

**Comment by rafaqz** [comment]
To get those values directly, you can call the functions
```julia
julia> crs(rast)
WellKnownText{GeoFormatTypes.CRS}(GeoFormatTypes.CRS(), "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID
[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\
"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9
122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"4326\"]]")

julia> extent(rast)
Extent(X = (57.3, 57.81916666666666), Y = (-20.533333333333335, -19.9725))
```

Resolution is slightly harder:
```julia
julia> step.(dims(rast))
(0.0008333333333333294, -0.0008333333333333367)
```

We don't show it because a raster does not always have a fixed resolution. E.g. a NetCDF often doesn't.

**Comment by Jigyasu4indp** [comment]
![er](https://github.com/rafaqz/Rasters.jl/assets/153259308/813ebab3-bbd1-4b57-a7cc-657148e43157)

**Comment by rafaqz** [comment]
Ahh sorry we should export that. You need to do `using Rasters.Extents`

**Comment by Jigyasu4indp** [comment]
OK 
![er_2](https://github.com/rafaqz/Rasters.jl/assets/153259308/ecf4268a-1f43-475e-bda8-5967a4400d02)

**Comment by rafaqz** [comment]
Yeah - so your Band dimension doesn't have resolution, of course.

so `step.(dims(gm, (X, Y))` will give you just the X/Y dims. 

If you have a time dimension it may have a resolution as well. This is what we should show by default - just the dimensions that do have a resolution.

**Comment by Jigyasu4indp** [comment]
This is working

**Comment by rafaqz** [comment]
Yeah, kind of ugly tho. Maybe a `resolution` function would help.

**Comment by Jigyasu4indp** [comment]
sure

**Comment by Jigyasu4indp** [comment]
Now using Rasters.Extents is not working.  Would you please suggest how to fix

**Comment by Jigyasu4indp** [comment]
![re](https://github.com/rafaqz/Rasters.jl/assets/153259308/aa004e15-505b-48ef-8d8a-ee47d3b932ed)

**Comment by rafaqz** [comment]
Old version again?

**Comment by Jigyasu4indp** [comment]
yes
