### ISSUE TITLE
Can't open netcdf file as Raster 

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#605]
We can't open the NetCDF file from this link as as Raster even though you can open it with NCDatasets. 
https://acd-ext.gsfc.nasa.gov/anonftp/toms/tmp/dhaffner/VJ102MOD.A2022017.0218.021.2022017084708.nc

The Netcdf file is nested and the actual data is organised in groups at a deeper level.
One can construct a Raster, by opening the data with NCDatasets and using one of the subgroups but that is cumbersome.

See this discourse discussion;
https://discourse.julialang.org/t/truecolor-raster-satellite-image/111401/8

**Comment by rafaqz** [comment]
https://cfconventions.org/cf-conventions/cf-conventions.html#groups

Should we add a `group` keyword to get a Raster/RasterStack of a particular group?

**Comment by rafaqz** [comment]
We have a `group` keyword now.
