### ISSUE TITLE
Values of missingval still shown in the overview of the Raster

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Rasters.jl#610]
I am still working with the data from #605 and I am constructing a Raster object from the Netcdf subgroup. 
Setting the missingval keyword seems to have no effect and I can still see the missingval in the array when the Raster is shown. 

This is a reproducer with small data:

```julia
arr = rand(10,10)
r = Raster(arr, (X(1:10,Y(1:10)), missingval=arr[1,1])
```

I would have expected that the first element of the Raster is shown as missing.
`skipmissing` works as expected.

**Comment by rafaqz** [comment]
It doesnt do sentinel missings by default. That has never been implemented and I rarely want it myself becapuse uts slow. So it needs to be optional.

If you can write out a syntax and specific behaviours in lazy/non lazy modes we can implement it.
