### ISSUE TITLE
verbose = false in `rasterize` does not suppress "Info"

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#624]
Turning off verbose in `rasterize` does not suppress "Info". If this is not the intended functionality I can issue a PR.

**Comment by rafaqz** [comment]
Yeah its meant to supress it

**Comment by alex-s-gardner** [comment]
When you misspell `verbose` as `verbos` ... this is what happens..

**Comment by rafaqz** [comment]
Lol. Swallowing incorrect keywords is still an issue, but we have #371 already
