### ISSUE TITLE
`trim` scales poorly with number of dimensions

### ISSUE THREAD

**Issue by tiemvanderdeure** [rafaqz/Rasters.jl#629]
`trim` is suddenly much slower if a `Raster` has 5 or more dimensions. 

A simple example:
```julia
using Rasters, DimensionalData
ras = Raster(rand(X(1:1000), Y(1:1000), Z(1:2), Ti(1:2), Band(1:2))) |> replace_missing
ras2 = mergedims(ras, (Z, Ti, Band) => Z)

@time Rasters.trim(ras);
@time Rasters.trim(ras2);
@time Rasters.trim(ras[Z(1)]);
@time Rasters.trim(ras[Z(1), Ti(1)]);
@time Rasters.trim(ras[Z(1), Ti(1), Band(1)]);

```

Which on the second run (after compilation) returns
```
  4.345814 seconds (39.82 M allocations: 2.262 GiB, 31.79% gc time)
  0.170971 seconds (29 allocations: 28.695 KiB)
  0.121606 seconds (33 allocations: 34.359 MiB, 15.13% gc time)
  0.054238 seconds (32 allocations: 17.192 MiB)
  0.024460 seconds (32 allocations: 8.609 MiB)
```

The last three roughly half each time, as expected. But the case with 5 dimensions suddenly has lots of allocations. It is also 20 times slower than the raster with the same data but merged dimensions and 40 times slower than the 4-dimensional raster (so half the size).

**Comment by rafaqz** [comment]
Sounds like type instability in `map` with more than 4 mixed type arguments. We may need a few generated functions to fix this for arbitrary dimensions. A profiling flame graph should show this if you want to post one.

**Comment by rafaqz** [comment]
![2024-04-09-135822_1920x1080_001](https://github.com/rafaqz/Rasters.jl/assets/2534009/44f5a97e-e8fa-44d8-abb6-c3078f47188b)

Its in `setindex!` on `AxisATracker. Its literally just missing an `@inline`, and that fixes performance completely. It may be that base is giving up on inlining once the tuple gets big enough?

**Comment by rafaqz** [comment]
With:
```julia
@inline function Base.setindex!(A::AxisTrackers, x, I::Int...)
...
```

![2024-04-09-140638_1920x1080](https://github.com/rafaqz/Rasters.jl/assets/2534009/f7274677-e17a-4937-bf30-6068679ef04b)

**Comment by tiemvanderdeure** [comment]
Instructive!
