### ISSUE TITLE
Use Proj directly for reprojection

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Rasters.jl#634]
R is able to gain Julia equivalent speed by going directly through Proj instead of GDAL

**Comment by asinghvi17** [comment]
See kadyb/vector-benchmark#12

**Comment by rafaqz** [comment]
Yeah. It because we already had the dep.

**Comment by asinghvi17** [comment]
by the way, I just tested `proj_trans_generic` on an array (since I've been doing a bunch of reinterpret stuff :D) and it turns out, it is almost exactly the same timing as using `GI.reproject`!

**Comment by rafaqz** [comment]
Yeah tried that too in the past. Julias C calls are so fast it makes no difference
