### ISSUE TITLE
slow speed in write nc

### ISSUE THREAD

**Issue by kongdd** [rafaqz/Rasters.jl#642]
It costs about 80s to save a Raster with a dimension of 3600*1500 into nc with `Rasters.jl`.
While, in comparison, `NCDatasets` only costs 2s.

```julia
using Rasters
using NCDatasets

f = "./LAI_mean_Global_WHIT_2000-2023.nc"
@time ra = Raster(f, lazy=false)

@time write("temp.nc", ra; force=true)
@time write("temp.nc", ra; force=true)

# 105.611572 seconds (272.79 M allocations: 11.790 GiB, 1.76% gc time)
# 77.975531 seconds (272.79 M allocations: 11.790 GiB, 2.06% gc time)
```

[LAI_mean_Global_WHIT_2000-2023.zip](https://github.com/rafaqz/Rasters.jl/files/15102375/LAI_mean_Global_WHIT_2000-2023.zip)

**Comment by rafaqz** [comment]
Should be fixed already on main

**Comment by rafaqz** [comment]
Just work on `main` for now ;)

Hopefully before next week there will be a new version, but I've been thinking that for a month now so who knows

**Comment by rafaqz** [comment]
0.11.0 is registered now
