### ISSUE TITLE
stable docs link on github landing page broken

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#709]
Title says it all, results in 404 for me, dev works :)

**Comment by rafaqz** [comment]
Just click the home button from the 404 page for now. There is a bug in Vitepress with how Julia does docs paths.

The option is to hard link the latest version but it's a lot of work to update. So I don't know what to do because otherwise the docs are amazing.

**Comment by maxfreu** [comment]
Ah don't worry. Thought it'd be a quick fix. For me it's not important anyway, but I though maybe for new users. Feel free to close.

**Comment by rafaqz** [comment]
I mean, you can have a go, but others have failed before you!

@asinghvi17 is manually updating it on one of their packages, but I don't have time for that...

**Comment by rafaqz** [comment]
Oh can you automate the update in actions?

**Comment by asinghvi17** [comment]
Yep, see https://github.com/JuliaGeo/GeometryOps.jl/blob/gh-pages/.github/workflows/DeployDocs.yml (note it has to be in the `gh-pages` branch) then set your pages deploy method to "Actions".

**Comment by rafaqz** [comment]
And you don't need to do anything manual after that?

**Comment by asinghvi17** [comment]
Nothing manual no

**Comment by rafaqz** [comment]
This should be fixed on the next patch bump

**Comment by rafaqz** [comment]
Fixed, thanks for the code @asinghvi17
