### ISSUE TITLE
Docs build failing

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Rasters.jl#721]
```
ERROR: LoadError: Invalid text boundingbox GeometryBasics.HyperRectangle{3, Float64}([-156.29099924581053, 114.47999535256623, -Inf], [12.582000371861465, 21.61079966384172, 0.0])

```

I have no clue where this spawns from unfortunately...

**Comment by rafaqz** [comment]
Ugh these Mackie breaks on small version bumps are killing me

**Comment by lazarusA** [comment]
is this urgent? :D

**Comment by rafaqz** [comment]
It will be in the plots recipes tests somewhere, maybe cause by latest DD changes? Idk. 

If you wanna fix...

**Comment by lazarusA** [comment]
I had a similar issue in BeautifulMakie, also related to `text`, hopefully is not that hard to fix. I will take a look later today.

**Comment by asinghvi17** [comment]
I think this is in the docs build but it didn't throw an error...

**Comment by rafaqz** [comment]
Ohh right Makie plots in docs
