### ISSUE TITLE
Deprecation warning on v1.11

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Rasters.jl#731]
https://github.com/JuliaIO/Kerchunk.jl/actions/runs/10732898269/job/29765363495#step:6:478

```
│  WARNING: Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
│  You may need to write `f(x::Vararg{T})` rather than `f(x::Vararg{<:T})` or `f(x::Vararg{T}) where T` instead of `f(x::Vararg{T} where T)`.
```

Unfortunately, there's no associated line number information.

**Comment by rafaqz** [comment]
Yeah those are so annoying to find, the error is a hack in C or something

**Comment by rafaqz** [comment]
These should be gone now
