### ISSUE TITLE
Strange behavior in time to rasterize 

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#740]
I'm not sure if this is a GeometryOps @asinghvi17  issue or a Rasters issue.. but I get radically different rasterization times if I use data loaded from a shapefile (a few s) vrs. geometries handed from GeometricOps (a few hours) ???

```julia
#--------------- set local paths --------------- 
outrasterpath = "/Users/gardnera/data/its-live-data/velocity_mosaic/v2/static/cog"
outshapepath = "/Users/gardnera/data/global_vector_mask/"

# path2shapefile must be manually downloaded... google drive does not provide direct access... place files in outshapepath 
path2shapefile = "https://drive.google.com/file/d/1NeKbo_tiaiyAnd15QLN2mqzt-oPuWan3/view?usp=sharing"
#------------------------------------------------

# load packages
begin
    using Downloads
    using GDAL
    using Rasters
    import ArchGDAL
    using Shapefile
    using DataFrames
    using Plots
    using Images
    import GeometryOps as GO
    import GeoInterface as GI
    import GeoFormatTypes as GFT
    using GeoJSON
    using Proj
end

# download raster file
begin
    path2rasterfile = "https://its-live-data.s3.amazonaws.com/velocity_mosaic/v2/static/cog/ITS_LIVE_velocity_120m_RGI01A_0000_v02_vx.tif"
    fname = splitpath(path2rasterfile)[end]
    rasterfile = joinpath(outrasterpath, fname)

    if !isfile(rasterfile)
        f = Downloads.download(path2rasterfile, rasterfile)
    end
end

# download shapefile
varnames = ["not_ocean"]

# define some helper functions
begin
    function clip_or_empty(polygon, clipper)
        if GO.contains(polygon, clipper) # early return if polygon is completely inside clipper
            return GO.tuples(polygon)::Union{GI.Polygon,GI.MultiPolygon}
        end

        if GO.disjoint(polygon, clipper) # early return if polygon is completely outside clipper
            null_point = GI.is3d(polygon) ? (GI.ismeasured(polygon) ? (NaN, NaN, NaN, NaN) : (NaN, NaN, NaN)) : (NaN, NaN)
            contents = [GI.LinearRing([null_point, null_point, null_point])]
            return GO.tuples(GI.Polygon{GI.is3d(polygon),GI.ismeasured(polygon),typeof(contents),Nothing, typeof(GI.crs(polygon))}(contents, nothing, GI.crs(polygon)))
        end

        result = GO.intersection(polygon, clipper; target = GI.PolygonTrait())
        if isempty(result)
            null_point = GI.is3d(polygon) ? (GI.ismeasured(polygon) ? (NaN, NaN, NaN, NaN) : (NaN, NaN, NaN)) : (NaN, NaN)
            contents = [GI.LinearRing([null_point, null_point, null_point])]
            return GO.tuples(GI.Polygon{GI.is3d(polygon),GI.ismeasured(polygon),typeof(contents),Nothing, typeof(GI.crs(polygon))}(contents, nothing, GI.crs(polygon)))
        else
            return (GI.MultiPolygon(result; crs = GI.crs(polygon)))
        end
        # return GO.intersection(GO.GEOS(), polygon, clipper)
    end

    function bounds2rectangle(xbounds, ybounds)
        rectangle = GI.Wrappers.Polygon([[(xbounds[1], ybounds[1]), (xbounds[1], ybounds[2]), (xbounds[2], ybounds[2]), (xbounds[2], ybounds[1]), (xbounds[1], ybounds[1])]])
        return rectangle
    end
end

# read in raster
vx = Raster(rasterfile)
dx = dims(vx,:X)
dy = dims(vx, :Y)

xmin = -180;
ymin = 50;
xmax = -50;
ymax = 70;

mask = Dict()

# USING OGR2OGR [10s]
@time for varname = varnames
    shapefile = joinpath(outshapepath, "$varname.shp")
    outfile = tempname()*".shp"
    
    GDAL.ogr2ogr_path() do ogr2ogr
        run(`$ogr2ogr -clipsrc $xmin $ymin $xmax $ymax -t_srs EPSG:3413 $outfile $shapefile`)
    end

    feature = DataFrame(Shapefile.Table(outfile))
    mask[varname] = rasterize!(count, zeros(dx, dy), feature; threaded=false, verbose=false) .> 0
    p = heatmap(mask[varname]; title=varname)
    display(p)
end

# USING GeometryOps [Rasterize takes a few hours... at least that's what the progress bar tells me]
@time for varname = varnames
    shapefile = joinpath(outshapepath, "$varname.shp")

    feature = DataFrame(Shapefile.Table(shapefile));
    clipper = bounds2rectangle((xmin, xmax), (ymin, ymax))

    feature.geometry = clip_or_empty.(feature.geometry, (clipper,));
    feature.geometry = GO.reproject.(feature.geometry; source_crs = GFT.EPSG(4326), target_crs = GFT.EPSG(3031), calc_extent=true);

    mask[varname] = rasterize!(count, zeros(dx, dy),feature; threaded=false, verbose=false) .> 0

    p = heatmap(mask[varname]; title=varname)
    display(p)
end
```

**Comment by rafaqz** [comment]
Almost certainly type instability, check your geometry types

**Comment by rafaqz** [comment]
~~Almost certainly type instability, check your geometry types~~

Hmm maybe not just that, something weird happening here

**Comment by rafaqz** [comment]
Workflow points: 
- the manual downloading of a file and unzipping is a killer, can you put files somewhere else you can use `download`?
- extenal `run` calls are not reproducible MWE, and this one fails on my system. Better to use the function in GDAL.jl directly

Also this is mostly my hobby, and I'm finishing a PhD so deep in mind the tradeoffs: maybe I have e.g. ten minutes. Like 3 minutes to run this code and then maybe 7 to find the bug. If running the code me ten minutes the bug just wont be found.

**Comment by rafaqz** [comment]
One difference is you are converting to EPSG:3413 in the first example, and `3031` in the second. Your raster is HUGE and you have 200k geometries so you should expect slow times from anything - but the size and projections of your polygons can totally change the rasterisation time by a few orders of magnitude.

**Comment by rafaqz** [comment]
Ok, the reason is all your points are NaN ! The time is because for whatever reason indexing with an Extent of NaN in dimensional data just selects the whole array. So all 200,000 of those NaN polygons are being rasterized into 10000*20000 cells.

**Comment by asinghvi17** [comment]
Huh.  I guess that's a GeometryOps issue then, but I'm surprised all the numbers came out NaN.

Would it make sense for indexing by a NaN extent to return a 0 element array instead?

**Comment by rafaqz** [comment]
Looks like its just some of the points that Proj returns that are NaN, half of them are normal. But any `NaN` will give a `NaN` extent. maybe somewhere that clipping code is doing something different to `-clipsrc $xmin $ymin $xmax $ymax`

**Comment by rafaqz** [comment]
Oh lol @alex-s-gardner you are putting NaNs in there intentionally! Thats really not a thing NaN will leak everywhere.

**Comment by asinghvi17** [comment]
Yeah I put that there for empty geometries since they wouldn't plot otherwise (and I think reconstruct might also have failed at some point?)

**Comment by asinghvi17** [comment]
> Question is does that error, or does it return a zero length array.

I would say it should return a zero length array?  If it was a type issue, then it makes sense to error, but a user can't control what goes in to their geometries.  Maybe the metadata should contain a statement that it was indexed with a NaN and so returned an empty array, though.

**Comment by alex-s-gardner** [comment]
> Workflow points:
> 
> * the manual downloading of a file and unzipping is a killer, can you put files somewhere else you can use `download`? (so you know it just works)
> * extenal `run` calls are not reproducible MWE, and this one fails on my system. Better to use the function in GDAL.jl directly
> * The minimal part is really important, e.g. the loops here are not needed there is only one variable
> 
> Also this is mostly my hobby, and I'm finishing a PhD so keep in mind the tradeoffs: maybe I have e.g. ten minutes. Like 3 minutes to run this code and then maybe 7 to find the bug. If running the code takes me ten minutes the bug just wont be found.
> 
> The issues are great, keep them coming, but at the rate you make them we can talk about efficiency :)

Totally understandable.. it's easy to forget that this is hobby... truly impressive. I'll keep that all in mind for future issues.

**Comment by rafaqz** [comment]
Ok zero length it is. I think we need to fix GeoInterface and Extents to ignore NaN too, or you will lose real geoms from extent checks if there are any NaNs

**Comment by rafaqz** [comment]
DD now errors with NaN selectors, so this can't happen
