### ISSUE TITLE
recommendation: change `cellsize` to `cellarea`

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#747]
cellsize is a bit ambiguous, cell area is not

Also, it could be helpful if cellsize() accepted a kwarg of "unit" if the user wanted a unit other than km^2 returned. 

Given that projected units are always in meters, and meter is si units, I wonder if returning meters^2 by default would be a better choice in the long run.

**Comment by rafaqz** [comment]
I'll add unitful support soon for CF as well, so that can happen at the same time.

For `cellarea` PR and deprecated `cellsize`?

@tiemvanderdeure ?

**Comment by tiemvanderdeure** [comment]
I have no strong feelings about this one. The name cellsize comes from the function in terra in R with the same name: https://rdrr.io/cran/terra/man/cellSize.html. 

Changing to meter units would be breaking but it would make sense to do it at the same time as a name change.

**Comment by rafaqz** [comment]
I think we will have a `units` keyword for opt-in units wherever they're used, `false` by default.
