### ISSUE TITLE
`rasterize` is not covering the full extent of the input polygon

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Rasters.jl#749]
MWE:
[california_borders.geojson.txt](https://github.com/user-attachments/files/17055227/california_borders.geojson.txt)

```julia
using GeoJSON, Rasters, CairoMakie
california_borders = GeoJSON.read(read("california_borders.geojson.txt"))
raster = rasterize(california_borders; fill = 1, res = 0.5, shape = :line)

fig, ax, plt = plot(raster; colormap = cgrad(:Set3; categorical = true))
lines!(ax, california_borders; color = :darkgrey, linewidth = 1)
scatter!(ax, vec(DimPoints(raster)); markersize = 3, color = :black)
fig
```
<img src="https://github.com/user-attachments/assets/3b8bfdbf-14a2-4b37-9521-9880e322c1f3" height=350>

Note here that the top seems uncovered by the raster?!  Also it's not closed.

**Comment by rafaqz** [comment]
Ahh right it needs to use `Touches` for the extent somewhere.

**Comment by rafaqz** [comment]
Uggh this is an open/closed intervals problem. Probably I should actually use `Interval` internally to fix it cleanly.

Like the extent of a polygon is closed,closed but a raster is closed,open. So we are missing the points at the edges

**Comment by rafaqz** [comment]
![fixed](https://github.com/user-attachments/assets/f880c1a4-a387-4673-9ab0-9ebca26b162c)

Adding eps to upper bounds fixes it. I think I consolodated a bunch of separate code at some point in the past and broke it by treating all extents as the same. Maybe extents should hold intervals...

**Comment by asinghvi17** [comment]
Gotcha, looks like a doable fix then..

**Comment by rafaqz** [comment]
Yeah the qustion is if we fix it here or in Extents.jl.

Maybe Intervals in extents is a longer term problem, and I'll hack it here for now.

**Comment by rafaqz** [comment]
Ok this looks accurate to me now, as this `DimPoints` is the starts of the intervals

![fixed](https://github.com/user-attachments/assets/978d531d-172c-4b3d-9e1d-fa537f71fd08)

**Comment by asinghvi17** [comment]
Sweet!

Should DimPoints be defined as always being the center of the interval?  Is there a way one can specify that?

**Comment by rafaqz** [comment]
Yeah, hard to say. Despite the name it knows that its still `Intervals{Start}` and that will e.g. propagate through `similar`, broadcasts etc. Its just giving you the values in the lookups as points so changing them might be confusing.
