### ISSUE TITLE
Is there a good reason that `bounds` does not return an `Extent`?

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/Rasters.jl#757]
It seems like we should be converging on the use of Extents to describe bounds... for that reason I wonder why bounds doesn't return an Extent.

Along those lines I wonder why `Rasters.bounds` is not `Rasters.extent`

Just trying to think long-term here.

**Comment by rafaqz** [comment]
`extent` returns an extent! But maybe it should be exported.

Bounds are from before Extents existed.

**Comment by alex-s-gardner** [comment]
if we're moving in the direction of #755, it would be good to start exporting Extents... though I also wonder if the right approach is GI.RectangleTrait so that you can pass a GI rectangular geometry to functions like crop, rasterize, GO.polygonize, GO.clip.

Maybe `bounds` remains untouched and a new function `extents` is introduced that exports an Extent or a GI.RectangleTrait

**Comment by rafaqz** [comment]
Extents.extent is the function, we just need to export it

**Comment by alex-s-gardner** [comment]
closed with #758

**Comment by alex-s-gardner** [comment]
closed with #758
