### ISSUE TITLE
aggregate is type unstable for 

### ISSUE THREAD

**Issue by tiemvanderdeure** [rafaqz/Rasters.jl#759]
In my example, about half the time of aggregating is spent on `comparedims` which is called by `any(map(x -> x === missingval(src), block))`. 

MWE
```
ras = Raster(rand((X(1:1000), Y(1:1000), Z(1:3), Band(1:3), Ti(1:3))))
aggregate(sum, ras, (X(10), Y(10)));
```

![image](https://github.com/user-attachments/assets/17d9c400-02c5-48da-a4d1-3156acf175c6)

**Comment by rafaqz** [comment]
Oh I think this is fixed in the latest DD but Rasters doesn't support it yet

**Comment by tiemvanderdeure** [comment]
On DimensionalData 0.28:
![image](https://github.com/user-attachments/assets/0e6d15dc-a5d4-4246-b8e6-90726dda86bd)
