### ISSUE TITLE
Add random sampling functionality (like R's `terra::spatSample()`)

### ISSUE THREAD

**Issue by edwardlavender** [rafaqz/Rasters.jl#771]
Thanks for a great package! This is a feature request for a function like R’s `terra::spatSample()` that enables random sampling of locations on a raster, optionally excluding NaN/missing values. Below is some quick-and-dirty example code which demonstrates the functionality, but is inefficient when NaNs should be ignored. Maybe this is already quick & easy to do in Julia? (I am coming from R.)  

```julia
# Convert Raster to DataFrame, optionally dropping NaNs 
function asDataFrame(; x::Rasters.Raster, na_rm::Bool = true)
    # Get DataFrame
    xyz = DataFrame(x)
    rename!(xyz, ["x", "y", "z"])
    # Filter non NA cells 
    if na_rm
        xyz = xyz[.!isnan.(xyz.z), :]
    end
    return xyz
end 

# terra::spatSample() replacement, via asDataFrame()
function spatSample(; x::Rasters.Raster, size::Int64 = 1, na_rm::Bool = true)
    xyz = asDataFrame(x = x, na_rm = na_rm)
    xyz[sample(1:nrow(xyz), size, replace = true), :]
end 
```

**Comment by rafaqz** [comment]
No need for anything that complicated ;)

StatsBase gives us the `sample` method that will work on any `AbstractArray`. But we need to remove missing values from a raster first. To do that on pretty much any kind of iterator in Julia we just `skipmissing(obj)`. Then `collect` turns it into an array again as sampling over a lazy iterator like `skipmissing` returns cant work efficiently, and `sample` needs some `AbstractArray` input anyway. But this is it, here giving you 100 samples:
```julia
using StatsBase
sample(collect(skipmissing(raster)), 100)
```

**Comment by edwardlavender** [comment]
Thanks a lot for the quick response & detailed explanation! That is really helpful. That is a very nice solution for sampling values--but I was really hoping to sample both coordinates and values for non-NA cells, hence the use of `DataFrame()` above. Is there a simple way to do this that avoids converting the entire raster into a `DataFrame`? Thanks again!

**Comment by rafaqz** [comment]
It's probably no problem to convert, it's just `DataFrame(raster)`, just use `replace_missing` first for now.

`DataFrame(replace_missing(raster))`.

Then probably `sample` will work too.

**Comment by edwardlavender** [comment]
Fantastic - thank you!

**Comment by tiemvanderdeure** [comment]
I've been thinking about adding some sample function that mirrors syntax and outputs generated by `extract` - including the option to return coordinates. So good to know that more people want this and let's keep this issue open :)

**Comment by tiemvanderdeure** [comment]
This is now possible by calling `Rasters.sample(x, n; skipmissing = true)`!
