### ISSUE TITLE
Two missinval typos

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/Rasters.jl#792]
I just spotted a typo in an error message and searching for it yielded a second:

https://github.com/rafaqz/Rasters.jl/blob/e350b3f93e4af571982987f247b6efa75ff08eae/src/utils.jl#L30

https://github.com/rafaqz/Rasters.jl/blob/e350b3f93e4af571982987f247b6efa75ff08eae/ext/RastersNCDatasetsExt/ncdatasets_source.jl#L48

**Comment by rafaqz** [comment]
PR ?

**Comment by maxfreu** [comment]
![](https://media.makeameme.org/created/as-you-wish-a0c62f1908.jpg)

lol, looking up the right meme took as long as the PR xD

**Comment by rafaqz** [comment]
Add those `g`s or face my force lightning
