### ISSUE TITLE
`missing` is not materialized when elementwise dividing two rasters?

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Rasters.jl#797]
MWE:
```julia
using Rasters, RasterDataSources, ArchGDAL
precip = Raster(WorldClim{Climate}, :prec; month = 6)
areas = cellarea(precip)
precip ./ areas
```
 
![download-32](https://github.com/user-attachments/assets/577304e6-b9db-4d40-a583-39385246a6e1)

but the precip dataset has a bunch of missings.  I'm not really sure how this happened.

**Comment by asinghvi17** [comment]
The workaround I used was to mask both the rasters by the same geometry.  But that's not generally applicable.

**Comment by rafaqz** [comment]
You need to `replace_missing` first until the `cf` PR is merged

**Comment by asinghvi17** [comment]
Ah perfect, if that fixes it then I'll just leave the code in for now.
